import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GONZALVO
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    Connection con;
    Statement st;
    PreparedStatement pst;
    
    public static final String DbName = "pointofsale";
    
    public static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    
    public static final String DbUrl = "jdbc:mysql://localhost:3306/" + DbName;
    
    public static final String DbUsername = "root";
    
    public static final String DbPassword = "";
    
    
    public void Connection() throws SQLException{
        try {
            Class.forName(DbDriver);
            con = DriverManager.getConnection(DbUrl,DbUsername,DbPassword);
            st = con.createStatement();
            
            if (con != null){
                System.out.println("Connection Successful");
            }
         
            
                    } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLog1 = new javax.swing.JPanel();
        lbLoginLogo = new javax.swing.JLabel();
        jPanelLog2 = new javax.swing.JPanel();
        lbLoginTitle = new javax.swing.JLabel();
        lbLoginPassword = new javax.swing.JLabel();
        lbLoginUsername = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        btnLoginSubmit = new javax.swing.JButton();
        lbLoginQuestion = new javax.swing.JLabel();
        btnLoginLogin = new javax.swing.JButton();
        txtLoginPassword = new javax.swing.JPasswordField();
        loginViewPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLog1.setBackground(new java.awt.Color(80, 43, 15));
        jPanelLog1.setPreferredSize(new java.awt.Dimension(250, 350));

        lbLoginLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/knead to know (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanelLog1Layout = new javax.swing.GroupLayout(jPanelLog1);
        jPanelLog1.setLayout(jPanelLog1Layout);
        jPanelLog1Layout.setHorizontalGroup(
            jPanelLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLog1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lbLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanelLog1Layout.setVerticalGroup(
            jPanelLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLog1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lbLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jPanelLog2.setBackground(new java.awt.Color(251, 238, 215));
        jPanelLog2.setPreferredSize(new java.awt.Dimension(450, 0));

        lbLoginTitle.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        lbLoginTitle.setForeground(new java.awt.Color(80, 43, 15));
        lbLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLoginTitle.setText("LOGIN");
        lbLoginTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbLoginPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbLoginPassword.setForeground(new java.awt.Color(80, 43, 15));
        lbLoginPassword.setText("Password");

        lbLoginUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbLoginUsername.setForeground(new java.awt.Color(80, 43, 15));
        lbLoginUsername.setText("Username");

        txtLoginUsername.setBackground(new java.awt.Color(251, 238, 215));
        txtLoginUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLoginUsername.setForeground(new java.awt.Color(80, 43, 15));
        txtLoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsernameActionPerformed(evt);
            }
        });

        btnLoginSubmit.setBackground(new java.awt.Color(80, 43, 15));
        btnLoginSubmit.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnLoginSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginSubmit.setText("Login");
        btnLoginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSubmitActionPerformed(evt);
            }
        });

        lbLoginQuestion.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lbLoginQuestion.setForeground(new java.awt.Color(80, 43, 15));
        lbLoginQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLoginQuestion.setText("Don't have an acount?");

        btnLoginLogin.setBackground(new java.awt.Color(80, 43, 15));
        btnLoginLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginLogin.setText("Sign Up");
        btnLoginLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginLoginActionPerformed(evt);
            }
        });

        txtLoginPassword.setBackground(new java.awt.Color(251, 238, 215));
        txtLoginPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLoginPassword.setForeground(new java.awt.Color(80, 43, 15));
        txtLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginPasswordActionPerformed(evt);
            }
        });

        loginViewPassword.setBackground(new java.awt.Color(251, 238, 215));
        loginViewPassword.setForeground(new java.awt.Color(80, 43, 15));
        loginViewPassword.setText("View Password");
        loginViewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginViewPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLog2Layout = new javax.swing.GroupLayout(jPanelLog2);
        jPanelLog2.setLayout(jPanelLog2Layout);
        jPanelLog2Layout.setHorizontalGroup(
            jPanelLog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLog2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanelLog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLog2Layout.createSequentialGroup()
                        .addComponent(btnLoginLogin)
                        .addGap(133, 133, 133))
                    .addComponent(loginViewPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbLoginQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoginSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbLoginPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLoginUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLoginUsername, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtLoginPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jPanelLog2Layout.setVerticalGroup(
            jPanelLog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLog2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(lbLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(loginViewPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLoginQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginLogin)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLog2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelLog1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLog2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsernameActionPerformed

    private void btnLoginLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginLoginActionPerformed
        // TODO add your handling code here:
        Registration register = new Registration();
        register.setVisible(true);
        register.pack();
        register.setLocationRelativeTo(null);
        this.dispose();                        
    }//GEN-LAST:event_btnLoginLoginActionPerformed

    private void txtLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginPasswordActionPerformed

    private void loginViewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginViewPasswordActionPerformed
        // TODO add your handling code here:
        if (loginViewPassword.isSelected()){
            txtLoginPassword.setEchoChar((char)0);
        }else{
            txtLoginPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_loginViewPasswordActionPerformed

    private void btnLoginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSubmitActionPerformed
            // TODO add your handling code here:
        String username, password;

        username = txtLoginUsername.getText();
        password = txtLoginPassword.getText();

        // Use parameterized query to prevent SQL injection
        String queryLogin = "SELECT * FROM accountdetails WHERE accUsername = ? AND accPassword = ?";

        try {
            PreparedStatement pst = con.prepareStatement(queryLogin);
            pst.setString(1, username);
            pst.setString(2, password);

            ResultSet rs = pst.executeQuery();
            if (!rs.next()){
                JOptionPane.showMessageDialog(this, "Invalid Information. \nPlease check your username and password.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                txtLoginUsername.setText("");
                txtLoginPassword.setText("");
                System.out.println("Logging In...");
                // If the login is successful, instantiate and show the MainFrame
                MainFrame mainFrame = new MainFrame(username);  // assuming MainFrame can accept username as an argument
                mainFrame.setVisible(true);
                this.dispose();  // Close the login window
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginLogin;
    private javax.swing.JButton btnLoginSubmit;
    private javax.swing.JPanel jPanelLog1;
    private javax.swing.JPanel jPanelLog2;
    private javax.swing.JLabel lbLoginLogo;
    private javax.swing.JLabel lbLoginPassword;
    private javax.swing.JLabel lbLoginQuestion;
    private javax.swing.JLabel lbLoginTitle;
    private javax.swing.JLabel lbLoginUsername;
    private javax.swing.JCheckBox loginViewPassword;
    private javax.swing.JPasswordField txtLoginPassword;
    private javax.swing.JTextField txtLoginUsername;
    // End of variables declaration//GEN-END:variables
}
